# Generated by Django 5.0.6 on 2024-06-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_created_at_comment_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='main.comment'),
        ),
    ]
